import './SignUpInput'
import './SignInInput'
import './RequestNewPasswordInput'
import './ResetForgottenPasswordInput'
import './ChangePasswordInput'
import './DeleteAccountInput'
import './OAuthCodeInput'
